""" Invent new CUGN climatology figures (no pre-existing PNG to match).

Figures here go beyond the exact set Dan's MATLAB produced, but reuse the
section/Hovmöller plotting helpers and cmocean styling from
`cugn_climatology.regenerate_figure` for consistency.

Run:
    python -m cugn_climatology.new_figures
"""

import os

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import xarray as xr

# Reuse the section plotter (ports Dan's pxz.m), data/figure dirs, and topo loader.
from cugn_climatology.regenerate_figure import (plot_xz_section, DATA_DIR,
                                                FIG_DIR)

# Channel Islands that flank CUGN Line 90, as along-line offshore distances (km).
# Computed by nearest-approach of each island's position to the Line-90 lat/lon
# path in lt_mean_annual_cycle_depth_90.nc (Santa Catalina ~21 km off the line at
# ~60 km; San Clemente ~23 km off at ~95 km). Line 90 threads between them, as
# noted by Rudnick et al. (2017).
CHANNEL_ISLANDS_LINE90 = {'Santa Catalina I.': 60.0, 'San Clemente I.': 95.0}


def month_mean_dataset(ds, months=(1,), time_dim='time'):
    """ Average a seasonal-cycle dataset over calendar month(s).

    Collapses the 365-day `mean_annual_cycle` product to a single climatological
    field for the requested month(s), returned with a length-1 time dimension so
    the section plotters can consume it directly. `potential_density` (stored as
    a coordinate) is promoted to a variable so it survives as the contour
    overlay.

    Inputs
    ------
    ds : xr.Dataset
        A `mean_annual_cycle` product (dims time=365, depth, distance) whose
        time coordinate is cftime/datetime with a `.month` attribute.
    months : sequence of int
        Calendar months to average over (default January only).
    time_dim : str
        Name of the time dimension.

    Outputs
    -------
    xr.Dataset
        Month-averaged fields with a length-1 `time` dim.

    Generated by JXP and Claude.
    """
    # Make potential_density a normal variable so the mean/overlay keep it.
    if 'potential_density' in ds.coords:
        ds = ds.reset_coords('potential_density')

    # Boolean select of the requested calendar months (cftime-safe).
    mon = np.array([t.month for t in ds[time_dim].values])
    keep = np.isin(mon, months)
    sub = ds.isel({time_dim: np.where(keep)[0]}).mean(time_dim, skipna=True)

    # Restore a length-1 time dim for the section plotters.
    return sub.expand_dims(time_dim)


def figure_january_line90_channel_islands(outfile=None, xmax_km=200.0):
    """ Typical January temperature on CUGN Line 90, near the Channel Islands.

    Builds a cross-shore (distance x depth) section of the climatological
    January temperature on Line 90 from the long-term `mean_annual_cycle`
    product, zoomed to the inshore region where the line threads between Santa
    Catalina and San Clemente Islands, with those islands marked at their
    along-line positions. Potential-density contours are overlaid and the
    section styling (reversed axes, seafloor mask, cmocean thermal) is reused
    from `plot_xz_section` (ports Dan's pxz.m).

    Inputs
    ------
    outfile : str, optional
        Output PNG path; defaults to context/figs/new_jan_T_line90_islands.png.
    xmax_km : float
        Offshore extent to display (km); default 200 to frame the islands.

    Outputs
    -------
    outfile : str
        Path of the written PNG.

    Generated by JXP and Claude.
    """
    # Long-term full seasonal field (mean + annual cycle), Line 90.
    ds = xr.open_dataset(os.path.join(DATA_DIR,
                                      'lt_mean_annual_cycle_depth_90.nc'))
    jan = month_mean_dataset(ds, months=(1,))
    jan.attrs['line'] = '90'  # so plot_xz_section loads topo90 for the seafloor

    fig, ax = plt.subplots(figsize=(9, 6))
    # Reuse the section plotter: temperature fill + potential-density overlay.
    # A two-line title carries the "near the Channel Islands" framing without
    # colliding with the in-panel island labels.
    plot_xz_section(
        jan, 'temperature', itime=0, ax=ax,
        title='Typical January Temperature — CUGN Line 90\n'
              'Line threads between Santa Catalina and San Clemente Islands')
    ax.title.set_fontsize(11)

    # Zoom to the near-shore region that frames the Channel Islands.
    ax.set_xlim(xmax_km, 0)

    # Mark the islands at their along-line distances (dashed lines + labels).
    # The islands also appear as the shallow black bathymetry highs beneath.
    for name, xkm in CHANNEL_ISLANDS_LINE90.items():
        ax.axvline(xkm, color='0.15', ls='--', lw=1.2, zorder=6)
        ax.text(xkm, 20, f'{name} ', rotation=90, va='top', ha='center',
                fontsize=8, color='0.1', zorder=7,
                bbox=dict(boxstyle='round,pad=0.15', fc='white', ec='none',
                          alpha=0.7))

    fig.tight_layout()
    if outfile is None:
        os.makedirs(FIG_DIR, exist_ok=True)
        outfile = os.path.join(FIG_DIR, 'new_jan_T_line90_islands.png')
    fig.savefig(outfile, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {outfile}')
    return outfile


def main():
    """ Generate the January Line-90 Channel-Islands temperature figure.

    Generated by JXP and Claude.
    """
    figure_january_line90_channel_islands()


if __name__ == '__main__':
    main()
