""" Invent new CUGN climatology figures (no pre-existing PNG to match).

Figures here go beyond the exact set Dan's MATLAB produced, but reuse the
section/Hovmöller plotting helpers and cmocean styling from
`cugn_climatology.regenerate_figure` for consistency.

Run:
    python -m cugn_climatology.new_figures
"""

import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import cmocean
import xarray as xr

# Reuse the section plotter (ports Dan's pxz.m), data/figure dirs, topo loader,
# and the trailing-NaN trimming used by the Hovmöller helper.
from cugn_climatology.regenerate_figure import (plot_xz_section, DATA_DIR,
                                                FIG_DIR, _trim_time_padding)

# Channel Islands that flank CUGN Line 90, as along-line offshore distances (km).
# Computed by nearest-approach of each island's position to the Line-90 lat/lon
# path in lt_mean_annual_cycle_depth_90.nc (Santa Catalina ~21 km off the line at
# ~60 km; San Clemente ~23 km off at ~95 km). Line 90 threads between them, as
# noted by Rudnick et al. (2017).
CHANNEL_ISLANDS_LINE90 = {'Santa Catalina I.': 60.0, 'San Clemente I.': 95.0}


def month_mean_dataset(ds, months=(1,), time_dim='time'):
    """ Average a seasonal-cycle dataset over calendar month(s).

    Collapses the 365-day `mean_annual_cycle` product to a single climatological
    field for the requested month(s), returned with a length-1 time dimension so
    the section plotters can consume it directly. `potential_density` (stored as
    a coordinate) is promoted to a variable so it survives as the contour
    overlay.

    Inputs
    ------
    ds : xr.Dataset
        A `mean_annual_cycle` product (dims time=365, depth, distance) whose
        time coordinate is cftime/datetime with a `.month` attribute.
    months : sequence of int
        Calendar months to average over (default January only).
    time_dim : str
        Name of the time dimension.

    Outputs
    -------
    xr.Dataset
        Month-averaged fields with a length-1 `time` dim.

    Generated by JXP and Claude.
    """
    # Make potential_density a normal variable so the mean/overlay keep it.
    if 'potential_density' in ds.coords:
        ds = ds.reset_coords('potential_density')

    # Boolean select of the requested calendar months (cftime-safe).
    mon = np.array([t.month for t in ds[time_dim].values])
    keep = np.isin(mon, months)
    sub = ds.isel({time_dim: np.where(keep)[0]}).mean(time_dim, skipna=True)

    # Restore a length-1 time dim for the section plotters.
    return sub.expand_dims(time_dim)


def figure_january_line90_channel_islands(outfile=None, xmax_km=200.0):
    """ Typical January temperature on CUGN Line 90, near the Channel Islands.

    Builds a cross-shore (distance x depth) section of the climatological
    January temperature on Line 90 from the long-term `mean_annual_cycle`
    product, zoomed to the inshore region where the line threads between Santa
    Catalina and San Clemente Islands, with those islands marked at their
    along-line positions. Potential-density contours are overlaid and the
    section styling (reversed axes, seafloor mask, cmocean thermal) is reused
    from `plot_xz_section` (ports Dan's pxz.m).

    Inputs
    ------
    outfile : str, optional
        Output PNG path; defaults to context/figs/new_jan_T_line90_islands.png.
    xmax_km : float
        Offshore extent to display (km); default 200 to frame the islands.

    Outputs
    -------
    outfile : str
        Path of the written PNG.

    Generated by JXP and Claude.
    """
    # Long-term full seasonal field (mean + annual cycle), Line 90.
    ds = xr.open_dataset(os.path.join(DATA_DIR,
                                      'lt_mean_annual_cycle_depth_90.nc'))
    jan = month_mean_dataset(ds, months=(1,))
    jan.attrs['line'] = '90'  # so plot_xz_section loads topo90 for the seafloor

    fig, ax = plt.subplots(figsize=(9, 6))
    # Reuse the section plotter: temperature fill + potential-density overlay.
    # A two-line title carries the "near the Channel Islands" framing without
    # colliding with the in-panel island labels.
    plot_xz_section(
        jan, 'temperature', itime=0, ax=ax,
        title='Typical January Temperature — CUGN Line 90\n'
              'Line threads between Santa Catalina and San Clemente Islands')
    ax.title.set_fontsize(11)

    # Zoom to the near-shore region that frames the Channel Islands.
    ax.set_xlim(xmax_km, 0)

    # Mark the islands at their along-line distances (dashed lines + labels).
    # The islands also appear as the shallow black bathymetry highs beneath.
    for name, xkm in CHANNEL_ISLANDS_LINE90.items():
        ax.axvline(xkm, color='0.15', ls='--', lw=1.2, zorder=6)
        ax.text(xkm, 20, f'{name} ', rotation=90, va='top', ha='center',
                fontsize=8, color='0.1', zorder=7,
                bbox=dict(boxstyle='round,pad=0.15', fc='white', ec='none',
                          alpha=0.7))

    fig.tight_layout()
    if outfile is None:
        os.makedirs(FIG_DIR, exist_ok=True)
        outfile = os.path.join(FIG_DIR, 'new_jan_T_line90_islands.png')
    fig.savefig(outfile, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {outfile}')
    return outfile


def figure_oxygen_decline(line='90', xmax_km=200.0, outfile=None):
    """ Dissolved-oxygen decline at depth over 2017-2026 on a CUGN line.

    Two panels, sharing a depth axis:
      (a) a time-depth Hovmoller of the inshore-averaged dissolved-oxygen
          anomaly (cmocean balance), whose shift from positive (early record) to
          negative (late record) is the deoxygenation; and
      (b) the linear trend of that anomaly vs depth (mumol/kg per decade),
          marking the depth of strongest decline.
    Oxygen (`doxy`) exists only in the short-term (`st`, 2017-2025) products, so
    those are used. The time-depth panel layout follows Dan's `ptimez.m`
    (time on x, depth on y, reversed).

    Caveat: over the ~9.5-yr record the trend is endpoint-sensitive (an
    oxygen-rich 2018-19 start pulls the slope negative); it is better read as
    multi-year variability than a proven secular trend. This is annotated on the
    figure.

    Inputs
    ------
    line : str
        Two-character line id (default '90'); oxygen is present on all st lines.
    xmax_km : float
        Inshore cross-shore averaging limit (km, default 200).
    outfile : str, optional
        Output PNG; defaults to context/figs/new_o2_decline_line<line>.png.

    Outputs
    -------
    outfile : str, the written PNG path.

    Generated by JXP and Claude.
    """
    ds = xr.open_dataset(os.path.join(DATA_DIR, f'st_anomaly_depth_{line}.nc'))
    ds = _trim_time_padding(ds)

    # Inshore-averaged dissolved-oxygen anomaly -> (time, depth).
    o2 = ds['doxy'].sel(distance=slice(0, xmax_km)).mean('distance', skipna=True)
    t = pd.to_datetime(ds['time'].values)
    depth = ds['depth'].values

    # Linear trend per depth (umol/kg per decade), on the inshore-averaged series.
    tyr = (t - t[0]).days.values / 365.25
    trend = np.full(depth.size, np.nan)
    for iz in range(depth.size):
        y = o2.isel(depth=iz).values
        good = np.isfinite(y)
        if good.sum() > 10:  # need enough points for a meaningful slope
            trend[iz] = np.polyfit(tyr[good], y[good], 1)[0] * 10.0
    iz_max = int(np.nanargmin(trend))          # depth of strongest decline
    z_max, tr_max = depth[iz_max], trend[iz_max]

    fig, (axH, axT) = plt.subplots(
        1, 2, figsize=(13, 6), sharey=True, constrained_layout=True,
        gridspec_kw=dict(width_ratios=[3, 1]))

    # (a) Time-depth Hovmoller of the O2 anomaly, symmetric balance scale.
    field = o2.transpose('depth', 'time').values
    vmax = np.ceil(np.nanpercentile(np.abs(field), 99))
    levels = np.linspace(-vmax, vmax, 21)
    pc = axH.contourf(t, depth, field, levels=levels, cmap=cmocean.cm.balance,
                      extend='both')
    axH.set_ylim(depth.max(), 0)             # depth increases downward
    axH.axhline(z_max, color='k', ls='--', lw=1)   # strongest-decline depth
    axH.set_xlabel('Time'); axH.set_ylabel('Depth (m)')
    axH.set_title(f'(a) Line {line}.0 dissolved-oxygen anomaly, inshore '
                  f'0-{xmax_km:.0f} km')
    cb = plt.colorbar(pc, ax=axH, pad=0.02)
    cb.set_label('O$_2$ anomaly ($\\mu$mol kg$^{-1}$)')

    # (b) Trend vs depth; negative = deoxygenation.
    axT.plot(trend, depth, '-o', color='tab:red', ms=3, lw=1.5)
    axT.axvline(0, color='0.5', lw=0.8)
    axT.axhline(z_max, color='k', ls='--', lw=1)
    axT.plot(tr_max, z_max, 'ko', ms=6)
    # Place the callout in open space (right of the curve) with an arrow.
    axT.annotate(f'max decline\n{tr_max:.0f} $\\mu$mol kg$^{{-1}}$/decade\n'
                 f'at {z_max:.0f} m',
                 xy=(tr_max, z_max), xytext=(0.45, 0.30),
                 textcoords='axes fraction', fontsize=8, va='center', ha='left',
                 arrowprops=dict(arrowstyle='->', lw=0.8))
    axT.set_xlabel('Trend ($\\mu$mol kg$^{-1}$ decade$^{-1}$)')
    axT.set_title('(b) O$_2$ trend')
    axT.grid(alpha=0.3)

    fig.suptitle(f'Dissolved-oxygen decline at depth — CUGN Line {line}.0 '
                 f'(short-term, 2017–2026)', fontsize=12)
    # Endpoint-sensitivity caveat.
    fig.text(0.5, -0.02,
             'Trend over a ~9.5-yr record is endpoint-sensitive (oxygen-rich '
             '2018–19 start) — interpret as multi-year variability.',
             ha='center', fontsize=8, style='italic', color='0.35')

    if outfile is None:
        os.makedirs(FIG_DIR, exist_ok=True)
        outfile = os.path.join(FIG_DIR, f'new_o2_decline_line{line}.png')
    fig.savefig(outfile, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {outfile} (max decline {tr_max:.1f} umol/kg/decade at {z_max:.0f} m)')
    return outfile


def main():
    """ Generate the invented new figures.

    Generated by JXP and Claude.
    """
    figure_january_line90_channel_islands()
    figure_oxygen_decline('90')


if __name__ == '__main__':
    main()
