""" Regenerate CUGN cross-shore section figures in Python.

This module reproduces the "map xz" section plots that Dan Rudnick's MATLAB
pipeline generates for the 2026 beta climatology, working from the shipped
NetCDF products rather than the MATLAB `.mat` intermediates.

Provenance / MATLAB functions that guided this code (in
`$OS_SPRAY/CUGN/Climatology/Original/src_231/`):
  - `pxz.m`             -- the cross-shore section plotter this ports: filled
                           color field for one variable, black potential-density
                           (sigma-theta) contours overlaid, reversed offshore
                           and depth axes, "Line <id>, <date|Mean>" title, and a
                           black seafloor mask.
  - `makemapplots.m`    -- driver that calls `pxz` for the time-varying `map`
                           (total) product; sets the sigma overlay contour
                           levels (20:0.25:30, heavy integers 20:30) and uses
                           automatic color levels for the field.
  - `makemeanmapplots_var.m` / `makeseasonsplots_var.m` -- sibling drivers whose
                           fixed field levels (T 5:0.5:17, S 32.8:0.05:34.3)
                           informed the 0.5-degree temperature spacing here.
  - `topomask.m` (+ `topo66.mat`) -- source of the per-line bathymetry used for
                           the seafloor mask (`area(...)` in MATLAB).

Style follows the project decision to use `cmocean` colormaps (thermal for
temperature, haline for salinity, balance for anomalies) in place of the MATLAB
`jet`/`redblue`, while keeping Dan's contour levels and layout.

Run:
    python -m cugn_climatology.regenerate_figure
"""

import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import cmocean
import xarray as xr
from scipy.io import loadmat

# Data + output locations (see context/context_cugn_2026beta.md).
DATA_DIR = os.path.join(os.environ['OS_SPRAY'], 'CUGN', 'Climatology', '2026 beta')
SRC231_DIR = os.path.join(os.environ['OS_SPRAY'], 'CUGN', 'Climatology',
                          'Original', 'src_231')
FIG_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       'context', 'figs')

# Sigma-theta (potential density) overlay contour levels, from makemapplots.m:
# regular contours every 0.25 kg/m^3, heavy+labeled contours on integers.
SIGMA_CONT = np.arange(20.0, 30.0 + 0.001, 0.25)
SIGMA_CONT_HEAVY = np.arange(20.0, 30.0 + 0.001, 1.0)

# Per-variable display style: cmocean colormap + colorbar label. The MATLAB
# equivalents (pxz.m) were jet for scalars and redblue for velocity/anomaly.
VAR_STYLE = {
    'temperature':          dict(cmap=cmocean.cm.thermal, label='Temperature (°C)'),
    'salinity':             dict(cmap=cmocean.cm.haline,  label='Salinity (psu)'),
    'potential_temperature':dict(cmap=cmocean.cm.thermal, label='Potential Temperature (°C)'),
    'chlorophyll_a':        dict(cmap=cmocean.cm.algae,   label='Chlorophyll (mg/m$^3$)'),
    'doxy':                 dict(cmap=cmocean.cm.oxy,     label='Dissolved Oxygen ($\\mu$mol/kg)'),
    'acoustic_backscatter': dict(cmap=cmocean.cm.matter,  label='Acoustic Backscatter (dB)'),
    'geostrophic_velocity': dict(cmap=cmocean.cm.balance, label='Geostrophic Velocity (m/s)'),
    'doppler_velocity_along':  dict(cmap=cmocean.cm.balance, label='Alongshore Velocity (m/s)'),
    'doppler_velocity_across': dict(cmap=cmocean.cm.balance, label='Across-shore Velocity (m/s)'),
}


def load_topography(line, src_dir=SRC231_DIR):
    """ Load a CUGN line's bottom topography for the seafloor mask.

    Ports the data load in Dan's `topomask.m` / `topo<line>.mat`.

    Inputs
    ------
    line : str
        Two-character line id, e.g. '66'.
    src_dir : str
        Directory holding `topo<line>.mat`.

    Outputs
    -------
    (dist, topo) : tuple of 1-D numpy arrays
        Offshore distance (km) and bottom depth (m) along the line, or
        (None, None) if the file is absent.

    Generated by JXP and Claude.
    """
    path = os.path.join(src_dir, f'topo{line}.mat')
    if not os.path.exists(path):
        return None, None
    m = loadmat(path)
    return np.squeeze(m['dist']).astype(float), np.squeeze(m['topo']).astype(float)


def plot_xz_section(ds, var, itime, ax=None, field_levels=None,
                    overlay='potential_density', title=None):
    """ Plot a cross-shore (distance x depth) section, porting Dan's `pxz.m`.

    Draws a filled color field for `var` with black potential-density contours
    overlaid, the offshore axis reversed (far offshore on the left, coast at
    right) and depth increasing downward, matching the MATLAB layout. Uses a
    cmocean colormap per the project style decision.

    Inputs
    ------
    ds : x.Dataset
        A depth-coordinate CUGN product (dims time, depth, distance) holding
        `var` and, for the overlay, `potential_density`.
    var : str
        Variable to color-fill (e.g. 'temperature').
    itime : int
        Time index to plot (a single section).
    ax : matplotlib Axes, optional
        Target axes; a new figure/axes is created if omitted.
    field_levels : array-like, optional
        Filled-contour levels. If None, 0.5-unit-spaced levels spanning the
        data are used (mirroring pxz.m's automatic levels refined to dc/2).
    overlay : str or None
        Variable drawn as black contours (default 'potential_density'); None
        to skip.
    title : str, optional
        Axes title; if None, built as "Line <id>, <date>".

    Outputs
    -------
    (ax, mappable) : the axes and the filled-contour mappable (for a colorbar).

    Generated by JXP and Claude.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(9, 6))

    # Coordinates: distance (km) on x, depth (m) on y.
    x = ds['distance'].values
    z = ds['depth'].values
    field = ds[var].isel(time=itime).transpose('depth', 'distance').values

    # Render masked/NaN cells as black "seafloor" rather than white. Dan's MATLAB
    # plots the UN-masked `map` field (filled edge-to-edge by the objective map)
    # and paints bathymetry on top, so no white shows near the coast. We instead
    # plot the shipped, already-topo/error-masked product, whose NaN wedge near
    # the coast would otherwise show through `contourf` as the (white) axes
    # background. A black facecolor makes those masked cells read as seafloor.
    ax.set_facecolor('k')
    # Pad a surface row (0 m = the 10 m values) so the color field reaches the
    # top of the axes instead of leaving a thin black band above the 10 m bin.
    z = np.concatenate(([0.0], z))
    field = np.vstack([field[0:1, :], field])

    # Automatic 0.5-unit color levels spanning the data (cf. pxz.m dc/2 logic),
    # unless the caller pins them.
    if field_levels is None:
        lo = np.floor(np.nanmin(field) * 2) / 2.0
        hi = np.ceil(np.nanmax(field) * 2) / 2.0
        field_levels = np.arange(lo, hi + 0.5, 0.5)

    style = VAR_STYLE.get(var, dict(cmap=cmocean.cm.thermal, label=var))

    # Filled color field (extend='both' mirrors Dan's extended colorbar 'extbar').
    mappable = ax.contourf(x, z, field, levels=field_levels,
                           cmap=style['cmap'], extend='both')

    # Black potential-density contours: regular + heavy/labeled (pxz.m var2).
    if overlay is not None and overlay in ds:
        ovl = ds[overlay].isel(time=itime).transpose('depth', 'distance').values
        ovl = np.vstack([ovl[0:1, :], ovl])  # pad the surface row to match z
        light = [c for c in SIGMA_CONT if c not in SIGMA_CONT_HEAVY]
        ax.contour(x, z, ovl, levels=light, colors='k', linewidths=0.5)
        ch = ax.contour(x, z, ovl, levels=SIGMA_CONT_HEAVY, colors='k',
                        linewidths=1.5)
        ax.clabel(ch, fmt='%d', fontsize=8)

    # Seafloor mask: fill below the bottom in black (MATLAB `area(...)`).
    line = str(ds.attrs.get('line', '66'))[:2] if 'line' in ds.attrs else '66'
    tdist, ttopo = load_topography(line)
    if tdist is not None:
        ax.fill_between(tdist, ttopo, z.max(), facecolor='k', zorder=5)

    # Axes: reverse offshore (pxz.m 'xdir','rev') and depth downward ('ydir','rev').
    ax.set_xlim(x.max(), x.min())
    ax.set_ylim(z.max(), z.min())
    ax.set_xlabel('Offshore Distance (km)')
    ax.set_ylabel('Depth (m)')

    if title is None:
        date = pd.to_datetime(ds['time'].values[itime]).strftime('%Y/%m/%d')
        title = f'Line 66.7, {date}'
    ax.set_title(title)

    cb = plt.colorbar(mappable, ax=ax)
    cb.set_label(style['label'])
    return ax, mappable


def regenerate_temperature_line66(date='2026-01-11', outfile=None):
    """ Regenerate the Line 66 total-temperature section for a given date.

    Reproduces Dan's `66_map_xz_t_<date>.png` (via `makemapplots.m` -> `pxz.m`)
    from `lt_total_depth_66.nc`, selecting the nearest available 10-day step.

    Inputs
    ------
    date : str
        Target date (YYYY-MM-DD); the nearest section date is used.
    outfile : str, optional
        Output PNG path; defaults to context/figs/regen_66_map_xz_t_<date>.png.

    Outputs
    -------
    outfile : str
        Path of the written PNG.

    Generated by JXP and Claude.
    """
    ds = xr.open_dataset(os.path.join(DATA_DIR, 'lt_total_depth_66.nc'))

    # Nearest 10-day section to the requested date.
    times = pd.to_datetime(ds['time'].values)
    itime = int(np.abs(times - pd.Timestamp(date)).argmin())
    chosen = times[itime].strftime('%Y-%m-%d')

    fig, ax = plt.subplots(figsize=(9, 6))
    plot_xz_section(ds, 'temperature', itime, ax=ax)
    fig.tight_layout()

    if outfile is None:
        os.makedirs(FIG_DIR, exist_ok=True)
        outfile = os.path.join(FIG_DIR, f'regen_66_map_xz_t_{chosen}.png')
    fig.savefig(outfile, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {outfile} (section date {chosen})')
    return outfile


def main():
    """ Regenerate the Line 66 temperature section for 2026-01-11.

    Generated by JXP and Claude.
    """
    regenerate_temperature_line66('2026-01-11')


if __name__ == '__main__':
    main()
